---
title: "Telco Data Exploration"
author: "Rami"
date: "May 27, 2016"
output: html_document
---

# Setup

```{r}
library(dplyr)
library(knitr)
library(reshape2)
library(caret)
library(FactoMineR)
library(corrplot)
library(impute)
```

# Contract References

## Exploration

```{r}
glimpse(contracts)
contracts %>% summary()
```

```{r}
hist(contracts$AGE)
hist(as.integer(contracts$GENDER))
hist(as.integer(contracts$VALUE_SEGMENT))
handset_count <- length(levels(contracts$HANDSET_NAME))
hist(as.integer(contracts$HANDSET_NAME), breaks = handset_count)
```

## Outliers

```{r}
contracts %>% filter(AGE > 80, AGE < 99) %>% nrow
contracts %>% filter(AGE == 99) %>% nrow
contracts %>% filter(AGE < 0) %>% nrow
```

# Monthly Aggregates: train/test

## Exploration

```{r}
glimpse(monthly)
monthly %>% summary()
```

```{r}
hist(monthly$X206_SESSION_COUNT, breaks = 100)
hist(monthly$X206_USAGE, breaks = 100)
```

## Outliers

```{r}
summary(monthly)
```

# Roaming

## Exploration

```{r}
glimpse(roaming)
summary(roaming)
hist(roaming$USAGE, breaks = 100)
hist(roaming$SESSION_COUNT, breaks = 100)
```

## Outliers

```{r}
hist(roaming$CALL_MONTH_KEY)
hist(roaming$USAGE)
hist(roaming$SESSION_COUNT)
```

# Daily Aggregate

## Exploration

```{r}
glimpse(daily)
daily %>% summary()
```

## Outliers

```{r}
hist(daily$TOTAL_CONSUMPTION, breaks = 100)
hist(daily$NO_OF_SESSIONS, breaks = 100)
hist(as.integer(daily$FULL_DATE))
hist(as.integer(daily$ROAMING_FLAG))
```

# Combined: Monthly * Contracts * Roaming * Daily

## Exploration

```{r}
glimpse(train)
summary(train)
```

```{r}
glimpse(test)
summary(test)
```

```{r}
handsetOverview <- function(x) {
  x %>%
    group_by(HANDSET_NAME) %>%
    summarise(
      MU_USAGE_MU = (mean(X206_USAGE) + mean(X207_USAGE) + mean(X208_USAGE) + mean(X209_USAGE) + mean(X210_USAGE))/5,
      USERS = length(unique(CONTRACT_KEY)),
      TARGETS = ifelse(!is.null(x$TARGET), sum(TARGET), -1),
      PERC = ifelse(!is.null(x$TARGET), USERS/nrow(train), USERS/nrow(test))) %>%
    arrange(desc(USERS)) %>%
    head(n = 20)
}
cbind(handsetOverview(train), handsetOverview(test)) %>% kable(row.names = FALSE)
rm(handsetOverview)
```

```{r}
valuesegmentOverview <- function(x) {
  x %>%
    group_by(VALUE_SEGMENT) %>%
    summarise(
      MEAN_USAGE_MEAN = (mean(X206_USAGE) + mean(X207_USAGE) + mean(X208_USAGE) + mean(X209_USAGE) + mean(X210_USAGE))/5,
      USERS = length(unique(CONTRACT_KEY)),
      TARGETS = ifelse(!is.null(x$TARGET), sum(TARGET), -1),
      PERC = ifelse(!is.null(x$TARGET), USERS/nrow(train), USERS/nrow(test))) %>%
    arrange(desc(USERS)) %>%
    head(n = 20)
}
cbind(valuesegmentOverview(train), valuesegmentOverview(test)) %>% kable(row.names = FALSE)
rm(valuesegmentOverview)
```

```{r}
mean(train$TARGET)
```

All zeros benchmark = 0.5
Training data is skewed, while test data is symmetric.

# Visualization

```{r}
subs_train  <- train %>% select(GENDER, VALUE_SEGMENT, HANDSET_NAME)
subs_test   <- test %>% select(GENDER, VALUE_SEGMENT, HANDSET_NAME)
subs_data   <- rbind(subs_train, subs_test)

mca <- MCA(subs_data, graph = FALSE)
mca_vars <- data.frame(mca$var$coord)
mca_obs <- data.frame(mca$ind$coord, c(train$TARGET, rep(2, nrow(test))))
names(mca_obs) <- c("Dim.1", "Dim.2", "Dim.3", "Dim.4", "Dim.5", "TARGET")
```

```{r}
ggplot(data = mca_obs, aes(x = Dim.1, y = Dim.2)) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_point(size = 1, aes(colour = factor(TARGET), alpha = factor(TARGET))) +
  ggtitle("MCA plot of variables using R package FactoMineR") +
  scale_colour_discrete(name = "Target") +
  scale_alpha_manual(values = c(1, 1, 0.05))
```

```{r}
correlations <- cor(train %>% select(-c(AGE, GENDER, VALUE_SEGMENT, HANDSET_NAME, TARGET)))
corrplot(correlations, order = "hclust")
#highCorr <- findCorrelation(correlations, cutoff = 0.75)
#filtered <- train[, -highCorr]
```