---
title: "Teclo Feature Engineering"
author: "Rami"
date: "May 2, 2016"
output: html_document
---

# Setup

```{r}
options( java.parameters = "-Xmx12g" )
library(RWeka)
library(dplyr)
library(knitr)
library(reshape2)
```

```{r}
normalize <- function(x) {
  lower = min(x, na.rm = TRUE)
  upper = max(x, na.rm = TRUE)
  return((x - lower)/(upper - lower))
}
```

# Raw Data

```{r}
monthly <- read.csv("train.csv")
contracts <- read.csv("contract_ref.csv")
dates <- read.csv("calendar_ref.csv")
daily <- read.csv("daily_aggregate.csv")
roaming <- read.csv("roaming_monthly.csv")
testing <- read.csv("test.csv")

train <- merge(monthly, contracts)
test <- merge(testing, contracts)

detailed <- daily %>%
  rename(DATE_KEY = CALL_DATE_KEY) %>%
  merge(dates)
```

# Training Data (Monthly Aggregate * Contract Reference)

## Exploration

```{r}
glimpse(train)
train %>% summary()
```

```{r}
handsetOverview <- function(x) {
  x %>%
    group_by(HANDSET_NAME) %>% 
    summarise(
      MU_USAGE_MU = (mean(X206_USAGE) + mean(X207_USAGE) + mean(X208_USAGE) + mean(X209_USAGE) + mean(X210_USAGE))/5,
      USERS = length(unique(CONTRACT_KEY)),
      TARGETS = ifelse(!is.null(x$TARGET), sum(TARGET), -1),
      PERC = ifelse(!is.null(x$TARGET), USERS/nrow(train), USERS/nrow(test))) %>% 
    arrange(desc(USERS)) %>%
    head(n = 20)
}
cbind(handsetOverview(train), handsetOverview(test)) %>% kable(row.names = FALSE)
```

```{r}
rateplanOverview <- function(x) {
  x %>%
    group_by(RATE_PLAN) %>% 
    summarise(
      MEAN_USAGE_MEAN = (mean(X206_USAGE) + mean(X207_USAGE) + mean(X208_USAGE) + mean(X209_USAGE) + mean(X210_USAGE))/5,
      USERS = length(unique(CONTRACT_KEY)), 
      TARGETS = ifelse(!is.null(x$TARGET), sum(TARGET), -1),
      PERC = ifelse(!is.null(x$TARGET), USERS/nrow(train), USERS/nrow(test))) %>% 
    arrange(desc(USERS)) %>%
    head(n = 20)
}
cbind(rateplanOverview(train), rateplanOverview(test)) %>% kable(row.names = FALSE)
```

```{r}
valuesegmentOverview <- function(x) {
  x %>%
    group_by(VALUE_SEGMENT) %>% 
    summarise(
      MEAN_USAGE_MEAN = (mean(X206_USAGE) + mean(X207_USAGE) + mean(X208_USAGE) + mean(X209_USAGE) + mean(X210_USAGE))/5,
      USERS = length(unique(CONTRACT_KEY)), 
      TARGETS = ifelse(!is.null(x$TARGET), sum(TARGET), -1),
      PERC = ifelse(!is.null(x$TARGET), USERS/nrow(train), USERS/nrow(test))) %>% 
    arrange(desc(USERS)) %>%
    head(n = 20)
}
cbind(valuesegmentOverview(train), valuesegmentOverview(test)) %>% kable(row.names = FALSE)
```

```{r}
targetCor <- function(x) {
  x %>% 
    select(-c(CONTRACT_KEY, HANDSET_NAME, RATE_PLAN, GENDER, VALUE_SEGMENT)) %>% 
    cor() %>% 
    data.frame %>% select(TARGET)
}
targetCor(train)
```

```{r}
mean(train$TARGET)
```

All zeros benchmark = 0.5
Training data is skewed, while test data is symmetric.

## Feature Engineering

```{r}
featureCrafting <- function(data, target = TRUE) {
  res <- data
  
  levels(res$GENDER) <- c("F", "F", "F", "M", "M", "M",  "NA", "NA")
  levels(res$VALUE_SEGMENT) <- c("Core", "High", "Med-High", "Med-Low", "NA", "Platinum", "Premium")
  res$VALUE_SEGMENT[is.na(res$VALUE_SEGMENT)] <- "NA"

  if (target) {
    res <- res %>% select(-c(TARGET))
  }

  res <- res %>%
    mutate(AVG_USAGE = (X206_USAGE + X207_USAGE + X208_USAGE + X209_USAGE + X210_USAGE)/5) %>%
    mutate(X206_USAGE_DIFF = X206_USAGE - AVG_USAGE) %>%
    mutate(X207_USAGE_DIFF = X207_USAGE - AVG_USAGE) %>%
    mutate(X208_USAGE_DIFF = X208_USAGE - AVG_USAGE) %>%
    mutate(X209_USAGE_DIFF = X209_USAGE - AVG_USAGE) %>%
    mutate(X210_USAGE_DIFF = X210_USAGE - AVG_USAGE) %>%
    mutate(X206_TARGET = X206_USAGE_DIFF > 500) %>%
    mutate(X207_TARGET = X207_USAGE_DIFF > 500) %>%
    mutate(X208_TARGET = X208_USAGE_DIFF > 500) %>%
    mutate(X209_TARGET = X209_USAGE_DIFF > 500) %>%
    mutate(X210_TARGET = X210_USAGE_DIFF > 500) %>%
    mutate(X206_TARGET_INV = X206_USAGE_DIFF < -500) %>%
    mutate(X207_TARGET_INV = X207_USAGE_DIFF < -500) %>%
    mutate(X208_TARGET_INV = X208_USAGE_DIFF < -500) %>%
    mutate(X209_TARGET_INV = X209_USAGE_DIFF < -500) %>%
    mutate(X210_TARGET_INV = X210_USAGE_DIFF < -500) %>%
    mutate(AVG_SESS = (X206_SESSION_COUNT+X207_SESSION_COUNT+X208_SESSION_COUNT+X209_SESSION_COUNT+X210_SESSION_COUNT)/5) %>%
    mutate(X206_SESS_DIFF = X206_SESSION_COUNT - AVG_SESS) %>%
    mutate(X207_SESS_DIFF = X207_SESSION_COUNT - AVG_SESS) %>%
    mutate(X208_SESS_DIFF = X208_SESSION_COUNT - AVG_SESS) %>%
    mutate(X209_SESS_DIFF = X209_SESSION_COUNT - AVG_SESS) %>%
    mutate(X210_SESS_DIFF = X210_SESSION_COUNT - AVG_SESS) %>%
    mutate(X206_USAGE_SESS = X206_USAGE/X206_SESSION_COUNT) %>%
    mutate(X207_USAGE_SESS = X207_USAGE/X207_SESSION_COUNT) %>%
    mutate(X208_USAGE_SESS = X208_USAGE/X208_SESSION_COUNT) %>%
    mutate(X209_USAGE_SESS = X209_USAGE/X209_SESSION_COUNT) %>%
    mutate(X210_USAGE_SESS = X210_USAGE/X210_SESSION_COUNT)
  
  res <- res %>%
    mutate(AGE = normalize(AGE)) %>%
    mutate(AVG_USAGE = normalize(AVG_USAGE)) %>%
    mutate(AVG_SESS = normalize(AVG_SESS)) %>%
    mutate(X206_SESSION_COUNT = normalize(X206_SESSION_COUNT)) %>%
    mutate(X207_SESSION_COUNT = normalize(X207_SESSION_COUNT)) %>%
    mutate(X208_SESSION_COUNT = normalize(X208_SESSION_COUNT)) %>%
    mutate(X209_SESSION_COUNT = normalize(X209_SESSION_COUNT)) %>%
    mutate(X210_SESSION_COUNT = normalize(X210_SESSION_COUNT)) %>%
    mutate(X206_USAGE = normalize(X206_USAGE)) %>%
    mutate(X207_USAGE = normalize(X207_USAGE)) %>%
    mutate(X208_USAGE = normalize(X208_USAGE)) %>%
    mutate(X209_USAGE = normalize(X209_USAGE)) %>%
    mutate(X210_USAGE = normalize(X210_USAGE)) %>%
    mutate(X206_USAGE_DIFF = normalize(X206_USAGE_DIFF)) %>%
    mutate(X207_USAGE_DIFF = normalize(X207_USAGE_DIFF)) %>%
    mutate(X208_USAGE_DIFF = normalize(X208_USAGE_DIFF)) %>%
    mutate(X209_USAGE_DIFF = normalize(X209_USAGE_DIFF)) %>%
    mutate(X210_USAGE_DIFF = normalize(X210_USAGE_DIFF)) %>%
    mutate(X206_SESS_DIFF = normalize(X206_SESS_DIFF)) %>%
    mutate(X207_SESS_DIFF = normalize(X207_SESS_DIFF)) %>%
    mutate(X208_SESS_DIFF = normalize(X208_SESS_DIFF)) %>%
    mutate(X209_SESS_DIFF = normalize(X209_SESS_DIFF)) %>%
    mutate(X210_SESS_DIFF = normalize(X210_SESS_DIFF)) %>%
    mutate(X206_USAGE_SESS = normalize(X206_USAGE_SESS)) %>%
    mutate(X207_USAGE_SESS = normalize(X207_USAGE_SESS)) %>%
    mutate(X208_USAGE_SESS = normalize(X208_USAGE_SESS)) %>%
    mutate(X209_USAGE_SESS = normalize(X209_USAGE_SESS)) %>%
    mutate(X210_USAGE_SESS = normalize(X210_USAGE_SESS))

  binary_indicators <- cbind(
    model.matrix(~ VALUE_SEGMENT - 1, data = res) %>% data.frame(),
    model.matrix(~ GENDER - 1, data = res) %>% data.frame(),
    model.matrix(~ RATE_PLAN - 1, data = res) %>% data.frame()
    #model.matrix(~ HANDSET_NAME - 1, data = res) %>% data.frame()
  )

  res <- res %>%
    select(-c(VALUE_SEGMENT, GENDER, RATE_PLAN, HANDSET_NAME)) %>%
    cbind(binary_indicators)
  

  res <- res %>%
    select(-c(CONTRACT_KEY)) %>%
    cbind(data %>% select(CONTRACT_KEY)) %>%
    data.frame()
  
  if(target) {
    res <- res %>%
      cbind(data %>% select(TARGET)) %>%
      data.frame() %>%
      mutate(TARGET = as.logical(TARGET))
    res <- res %>% mutate(TARGET = as.factor(TARGET))
    levels(res$TARGET) <- c("0", "1")
  }

  return(res)
}

train <- train %>% featureCrafting(TRUE)
test <- test %>% featureCrafting(FALSE)
```

# Daily Aggregates

## Exploration

## Feature Engineering

```{r}
daily_sum <- detailed %>%
  group_by(CONTRACT_KEY, DATE_KEY) %>%
  mutate(USAGE = sum(TOTAL_CONSUMPTION), SESSIONS = sum(NO_OF_SESSIONS)) %>%
  ungroup() %>%
  select(CONTRACT_KEY, DATE_KEY, USAGE, SESSIONS) %>%
  unique()

daily_usage <- dcast(daily_sum, CONTRACT_KEY ~ DATE_KEY, value.var = "USAGE")
colnames(daily_usage) <- paste("USAGE", colnames(daily_usage), sep = "_")
daily_usage <- rename(daily_usage, CONTRACT_KEY = USAGE_CONTRACT_KEY)

daily_sessions <- dcast(daily_sum, CONTRACT_KEY ~ DATE_KEY, value.var = "SESSIONS")
colnames(daily_sessions) <- paste("SESSIONS", colnames(daily_sessions), sep = "_")
daily_sessions <- rename(daily_sessions, CONTRACT_KEY = SESSIONS_CONTRACT_KEY)
```

# Roaming

```{r}
glimpse(roaming)
summary(roaming)
```

```{r}
roaming_usage <- dcast(roaming, CONTRACT_KEY ~ CALL_MONTH_KEY, value.var = "USAGE")
colnames(roaming_usage) <- paste("ROAMING_USAGE", colnames(roaming_usage), sep = "_")
roaming_usage <- rename(roaming_usage, CONTRACT_KEY = ROAMING_USAGE_CONTRACT_KEY)
roaming_usage[is.na(roaming_usage)] <- 0

roaming_sessions <- dcast(roaming, CONTRACT_KEY ~ CALL_MONTH_KEY, value.var = "SESSION_COUNT")
colnames(roaming_sessions) <- paste("ROAMING_SESSIONS", colnames(roaming_sessions), sep = "_")
roaming_sessions <- rename(roaming_sessions, CONTRACT_KEY = ROAMING_SESSIONS_CONTRACT_KEY)
roaming_sessions[is.na(roaming_sessions)] <- 0
```

# Feature Selection

```{r}
AS <- make_Weka_filter("weka.filters.supervised.attribute.AttributeSelection")
CFS <- function(form, data) {
  return(AS(
    formula(form),
    data, control = Weka_control(
      E = "weka.attributeSelection.CfsSubsetEval",
      S = "weka.attributeSelection.GreedyStepwise")))
}
```

```{r}
CFS(TARGET ~ ., train) %>% glimpse()
```

# Output

```{r}
processFile <- function(fileName, targetPresent = TRUE) {
  res <- readFile(fileName, targetPresent)
  write.csv(res, paste("engineered.", fileName, sep = ''), row.names = FALSE)
  return(res)
}
```

```{r}
train <- processFile("train.csv")
```

```{r}
test <- processFile("test.csv", targetPresent = FALSE)
```