---
title: "Telco Project"
author: "Rami"
date: "May 20, 2016"
output: html_document
---

# Setup

```{r}
# options( java.parameters = "-Xmx12g" )
# library(MASS)
library(dplyr)
library(knitr)
# library(reshape2)
library(caret)
library(caretEnsemble)
library(beepr)
# library(FactoMineR)
# library(corrplot)
# library(e1071)
# library(randomForest)
# Let's not thrash my SSD to death for the sake of this project..
# library(doMC)
# registerDoMC(cores = 3)
library(DMwR)
library(ROSE)
```

```{r}
train <- read.csv("engineered.train.csv")
test <- read.csv("engineered.test.csv")
train$TARGET <- factor(train$TARGET)
levels(train$TARGET) <- c("Negative", "Positive")
set.seed(1337)
alternate_train_ds <- downSample(select(train, -CONTRACT_KEY, -TARGET), train$TARGET, yname = "TARGET")
# alternate_train_smote <- SMOTE(TARGET ~., data = select(train, -CONTRACT_KEY))
```

```{r}
export_res <- function (res, fname) {
  dframe <- cbind(as.integer(test$CONTRACT_KEY), as.integer(res) - 1) %>% data.frame
  names(dframe) <- c("CONTRACT_KEY", "PREDICTED_TARGET")
  dframe$CONTRACT_KEY <- as.integer(dframe$CONTRACT_KEY)
  dframe$PREDICTED_TARGET <- as.integer(dframe$PREDICTED_TARGET)
  write.csv(dframe, fname, row.names = FALSE, quote = FALSE)
}
```

# Partial Least Squares

```{r}
set.seed(1337)
model.pls <- train(x = select(alternate_train_ds, -TARGET),
                   y = alternate_train_ds$TARGET,
                   method = "pls",
                   tuneGrid = expand.grid(.ncomp = 10:25),
                   probMehod = "Bayes",
                   metric = "ROC",
                   na.action = na.pass,
                   trControl = trainControl(
                     #method = "cv",
                     number = 5,
                     classProbs = TRUE,
                     savePredictions = TRUE,
                     summaryFunction = twoClassSummary),
                   verbose = TRUE)
model.pls
confusionMatrix(model.pls)
beep("mario")
```

```{r}
pred.pls <- predict(model.pls, newdata = select(test, -CONTRACT_KEY))
summary(pred.pls)
```

# RPART

```{r}
set.seed(1337)
model.rpart <- train(x = select(alternate_train_ds, -TARGET),
                     y = alternate_train_ds$TARGET,
                     method = "rpart",
                     tuneLength = 10,
                     trControl = trainControl(
                       method = "cv",
                       number = 10,
                       classProbs = TRUE,
                       savePredictions = TRUE,
                       summaryFunction = twoClassSummary),
                     metric = "ROC")
model.rpart
confusionMatrix(model.rpart)
beep("complete")
```

```{r}
pred.rpart <- predict(model.rpart, newdata = test)
summary(pred.rpart)
```

# Random Forest

```{r}
set.seed(1337)
model.rf <-    train(x = select(alternate_train_ds, -TARGET),
                     y = alternate_train_ds$TARGET,
                     method = "rf",
                     #preProcess = "pca",
                     tuneGrid = expand.grid(.mtry = 7),
                     trControl = trainControl(
                       method = "boot",
                       number = 5,
                       classProbs = TRUE,
                       savePredictions = TRUE,
                       summaryFunction = twoClassSummary),
                     metric = "ROC")
model.rf
confusionMatrix(model.rf)
beep("fanfare")
```

```{r}
pred.rf <- predict(model.rf, newdata = test)
summary(pred.rf)
```

# Neural Network

```{r}
set.seed(1337)
model.nnet <- train(x = select(alternate_train_ds, -TARGET),
                    y = alternate_train_ds$TARGET,
                    method = "nnet",
                    metric = "ROC",
                    tuneLength = 2,
                    trace = FALSE,
                    trControl = trainControl(
                       method = "boot",
                       number = 5,
                       classProbs = TRUE,
                       savePredictions = TRUE,
                       summaryFunction = twoClassSummary))
model.nnet
confusionMatrix(model.nnet)
beep("ready")
```

```{r}
pred.nnet <- predict(model.nnet, newdata = test)
summary(pred.nnet)
```

# Least Squares SVM w/ RBF Kernel

```{r}
set.seed(1337)
model.svm <- train(x = select(alternate_train_ds, -TARGET),
                   y = alternate_train_ds$TARGET,
                   method = "lssvmRadial",
                   tuneLength = 5,
                   metric = "Kappa",
                   trControl = trainControl(
                      method = "cv",
                      number = 10,
                      savePredictions = TRUE))
model.svm
confusionMatrix(model.svm)
beep("ready")
```

```{r}
pred.svm <- predict(model.svm, newdata = test)
summary(pred.svm)
```

# kNN

```{r}
set.seed(1337)
model.knn <- train(x = select(alternate_train_ds, -TARGET),
                   y = alternate_train_ds$TARGET,
                   method = "knn",
                   metric = "ROC",
                   tuneLength = 5,
                   trControl = trainControl(
                      method = "boot",
                      number = 1,
                      classProbs = TRUE,
                      savePredictions = TRUE,
                      summaryFunction = twoClassSummary))
model.knn
confusionMatrix(model.knn)
beep("ready")
```

```{r}
pred.knn <- predict(model.knn, newdata = test)
summary(pred.knn)
```

# Bagged Logic Regression

```{r}
set.seed(1337)
model.lbg <- train(x = select(alternate_train_ds, -TARGET),
                   y = alternate_train_ds$TARGET,
                   method = "ORFpls",
                   metric = "ROC",
                   tuneLength = 2,
                   trControl = trainControl(
                      method = "boot",
                      number = 1,
                      classProbs = TRUE,
                      savePredictions = TRUE,
                      summaryFunction = twoClassSummary))
model.lbg
confusionMatrix(model.lbg)
beep("ready")
```

```{r}
pred.lbg <- predict(model.lbg, newdata = test)
summary(pred.lbg)
```


# Ensemble

```{r}
# all.models <- list(model.pls, model.nnet)
# names(all.models) <- sapply(all.models, function(x) x$method)
# sort(sapply(all.models, function(x) min(x$results$ROC)))
```

```{r}
set.seed(1337)
control <- trainControl(method = "boot",
                        number = 5,
                        savePredictions = TRUE,
                        classProbs = TRUE,
                        index = createResample(alternate_train_ds$TARGET, 5),
                        summaryFunction = twoClassSummary)

models <- list(pls = caretModelSpec(method = "pls",
                                    probMehod = "Bayes",
                                    metric = "ROC",
                                    tuneGrid = expand.grid(.ncomp = 1:20)),
               rf = caretModelSpec(method="rf",
                                   probMehod = "Bayes",
                                   metric = "ROC",
                                   tuneGrid=expand.grid(.mtry = 10),
                                   preProcess="pca"),
               nnet = caretModelSpec(method = "nnet",
                                     probMehod = "Bayes",
                                     metric = "ROC",
                                     tuneLength = 5),
               knn = caretModelSpect(method = "knn",
                                     probMethod = "Bayes",
                                     metric = "ROC",
                                     tuneLength = 5))

model.ensemble.list <- caretList(TARGET ~ .,
                                 data = alternate_train_ds,
                                 trControl = control,
                                 probMehod = "Bayes",
                                 tuneList = models,
                                 metric = "ROC")
model.ensemble.list
modelCor(resamples(model.ensemble.list))

model.ensemble <- caretEnsemble(model.ensemble.list,
                                probMehod = "Bayes",
                                metric = "ROC",
                                trControl = trainControl(
                                  method = "boot",
                                  number = 5,
                                  summaryFunction = twoClassSummary,
                                  classProbs = TRUE))
model.ensemble
confusionMatrix(model.ensemble$ens_model)
summary(model.ensemble)
rm(control, models)
beep("coin")
beep("treasure")
```

```{r}
pred.ensemble <- predict(model.ensemble, newdata = select(test, -CONTRACT_KEY))
summary(pred.ensemble)
```

# Stack

```{r}
model.stack <- caretStack(model.ensemble.list,
                          method = "gbm",
                          metric = "ROC",
                          tuneLength = 4,
                          trControl = trainControl(
                            method = "boot",
                            number = 5,
                            savePredictions = "final",
                            classProbs = TRUE,
                            summaryFunction = twoClassSummary))

model.stack
confusionMatrix(model.stack$ens_model)
summary(model.stack)
beep("shotgun")
beep("wilhelm")
```

```{r}
pred.stack <- predict(model.stack, newdata = select(test, -CONTRACT_KEY))
summary(pred.stack)
```

# Discriminant Analysis

```{r}
model.qda <- qda(TARGET ~ ., data = train)
```
