---
title: "Telco Project"
author: "Rami"
date: "May 1, 2016"
output: html_document
---

# Setup

```{r}
options( java.parameters = "-Xmx12g" )
library(RWeka)
library(dplyr)
library(knitr)
```

```{r}
trainClassifier <- function(classifier, data) {
  res <- classifier(TARGET ~ 
#                       X209_TARGET
#                     + X210_TARGET
#                     + VALUE_SEGMENT_CR
#                     + VALUE_SEGMENT_PR

#                         X210_USAGE
#                       + AVG_USAGE
#                       + X210_USAGE_DIFF
#                       + X209_TARGET
#                       + X210_TARGET
#                       + X210_USAGE_SESS
#                       + VALUE_SEGMENT_CR

  X210_USAGE                                    
+ X210_TARGET                                   
+ X206_TARGET_INV                               
+ X207_TARGET_INV                               
+ RATE_PLANBusiness.Unified.USB.3.5.GB          
+ RATE_PLANEmployee.VPN                         
+ RATE_PLANEnterprise.Shared.Data.Bundle        
+ RATE_PLANTE.Basic.Control                     
+ HANDSET_NAMEAcer.Liquid.S2.S520               
+ HANDSET_NAMEAlcatel.One.Touch.I216X.Pixi.7    
+ HANDSET_NAMEApple.iPhone.3GS                  
+ HANDSET_NAMEBlackBerry.9780                   
+ HANDSET_NAMEBlackBerry.Bold.9700              
+ HANDSET_NAMEBlackBerry.Curve.9300             
+ HANDSET_NAMEHuawei.E220                       
+ HANDSET_NAMEHuawei.E261                       
+ HANDSET_NAMEHuawei.E8231s.2                   
+ HANDSET_NAMEHuawei.MU709s.2                   
+ HANDSET_NAMEHuawei.NXT.L29                    
+ HANDSET_NAMELenovo.Lenovo.A7010a48            
+ HANDSET_NAMELG.E615.Optimus.L5.Dual           
+ HANDSET_NAMELG.G3.LTE.A                       
+ HANDSET_NAMELG.G3.Mini                        
+ HANDSET_NAMEMicrosoft.Lumia.950.XL            
+ HANDSET_NAMEMotorola.Moto.X..2nd.Gen..        
+ HANDSET_NAMEMotorola.Moto.X.Play              
+ HANDSET_NAMENokia.108.Dual.SIM                
+ HANDSET_NAMENokia.1120                        
+ HANDSET_NAMENokia.206.Dual.SIM                
+ HANDSET_NAMENokia.206.Dual.SIM..RM.872.       
+ HANDSET_NAMENokia.208.Dual.SIM                
+ HANDSET_NAMENokia.220                         
+ HANDSET_NAMENokia.225.Dual.SIM..RM.1011.      
+ HANDSET_NAMENokia.3100                        
+ HANDSET_NAMENokia.6120.Classic                
+ HANDSET_NAMENokia.Asha.210.Dual.SIM           
+ HANDSET_NAMENokia.Asha.302                    
+ HANDSET_NAMENokia.Asha.306                    
+ HANDSET_NAMENokia.Asha.502                    
+ HANDSET_NAMENokia.C5.06                       
+ HANDSET_NAMENokia.N95                         
+ HANDSET_NAMENokia.X2.05                       
+ HANDSET_NAMENokia.X3.00                       
+ HANDSET_NAMESamsung.C3312.Champ.Delux         
+ HANDSET_NAMESamsung.C3312R                    
+ HANDSET_NAMESamsung.C6712.Star.II.Duos        
+ HANDSET_NAMESamsung.E1205T                    
+ HANDSET_NAMESamsung.Galaxy.Star               
+ HANDSET_NAMESamsung.S5222R.Rex.80             
+ HANDSET_NAMESamsung.S5280.Galaxy.Star         
+ HANDSET_NAMESamsung.S6810.Galaxy.Fame         
+ HANDSET_NAMEShenzhen.Zowee.Technology.7000Q   
+ HANDSET_NAMESony.E6533..TBC.                  
+ HANDSET_NAMESony.Ericsson.LT18i.Xperia.arc.S  
+ HANDSET_NAMESony.Ericsson.LT26i.Xperia.S      
+ HANDSET_NAMESony.Ericsson.LT26w.Xperia.Arco.S 
+ HANDSET_NAMESony.Xperia.Z4.Compact            
+ HANDSET_NAMETecno.Telecom.7C                  
+ HANDSET_NAMEWBC.MO170                         
+ HANDSET_NAMEZTS.International.M10.S8.G300     
+ HANDSET_NAMEZTS.International.V5.A2           
+ TARGET                                        

# [1] "X210_USAGE"       "AVG_USAGE"        "X210_USAGE_DIFF"  "X209_TARGET"      "X210_TARGET"      "X210_USAGE_SESS"  "VALUE_SEGMENT_CR"
# [8] "TARGET

                    , data)
  return(res)
}
```

```{r}
predsave <- function(cls, dat, name) {
  res <- dat %>%
    mutate(PREDICTED_TARGET = predict(cls, dat)) %>%
    select(CONTRACT_KEY, PREDICTED_TARGET)
  res %>% write.csv(name, row.names = FALSE)
  return(res)
}
```

```{r}
classifierStats <- function(classifier) {
  entireDataSet <- summary(classifier)
  print(entireDataSet)
  print(calculateMetrics(entireDataSet))
  return(classifier)
}

compareWithKFold <- function(classifier, K = 12) {
  kfold <- evaluate_Weka_classifier(classifier, numFolds = K)
  print(kfold)
  print(calculateMetrics(kfold))
  return(kfold)
}

calculateMetrics <- function(kfold) {
  TP <- kfold$confusionMatrix[1, 1]
  TN <- kfold$confusionMatrix[2, 2]
  FP <- kfold$confusionMatrix[2, 1]
  FN <- kfold$confusionMatrix[1, 2]
  
  accuracy  <- (TP + TN) / (TP + TN + FP + FN)
  precision <- TP / (TP + FP)
  recall    <- TP / (TP + FN)
  f1        <- 2 * precision * recall / (precision + recall)
  
  res <- list(Accuracy = accuracy, Precision = precision, Recall = recall, F1 = f1)
  return(res)
}
```

```{r}
RF <- make_Weka_classifier("weka/classifiers/trees/RandomForest")
NB <- make_Weka_classifier("weka/classifiers/bayes/NaiveBayes")
MLP <- make_Weka_classifier("weka/classifiers/functions/MultilayerPerceptron")
MLP5 <- function(form, data, options = list(model = TRUE)) {
  # Faster training with only 5 epochs
  return(MLP(formula(form), data, control = Weka_control(N = 100), options = options))
}
C45Bagging <- function(form, data, options = list(model = TRUE)) {
  return(Bagging(formula(form), data, control = Weka_control(W = "weka.classifiers.trees.J48"), options = options))
}
```

# Data
```{r}
getCSV <- function(fileName, target = TRUE) {
  res <- read.csv(fileName)
  if (target)
    res <- res %>% mutate(TARGET = as.factor(TARGET))
  return(res)
}
```

```{r}
train <- getCSV("engineered.train.csv")
```

```{r}
test <- getCSV("engineered.test.csv", target = FALSE)
```

# Train
```{r}
cls.c45 <- trainClassifier(J48, train)
cls.c45.kfold <- cls.c45 %>% compareWithKFold()
```

```{r}
cls.rf <- trainClassifier(RF, train)
cls.rf.kfold <- cls.rf %>% compareWithKFold()
```

```{r}
#cls.smo <- trainClassifier(SMO, train)
#cls.smo.kfold <- cls.smo %>% compareWithKFold()
```

```{r}
cls.nb <- trainClassifier(NB, train)
cls.nb.kfold <- cls.nb %>% compareWithKFold()
```

```{r}
cls.mlp <- trainClassifier(MLP5, train)
cls.mlp.kfold <- cls.mlp %>% compareWithKFold()
```

```{r}
cls.bag <- trainClassifier(C45Bagging, train)
cls.bag.kfold <- cls.bag %>% compareWithKFold()
```

```{r}
cls.boost <- trainClassifier(AdaBoostM1, train)
cls.boost.kfold <- cls.boost %>% compareWithKFold()
```

```{r}
cls.logit <- trainClassifier(LogitBoost, train)
cls.logit.kfold <- cls.logit %>% compareWithKFold()
```

# Test

```{r}
res.boost <- predsave(cls.boost, test, "submission.boost.csv")
```

```{r}
res.rf <- predsave(cls.rf, test, "submission.forest.csv")
```

```{r}
res.bag <- predsave(cls.bag, test, "submission.bag.csv")
```

```{r}
res.nb <- predsave(cls.nb, test, "submission.bayes.csv")
```

```{r}
res.c45 <- predsave(cls.c45, test, "submission.c45.csv")
```

```{r}
res.logit <- predsave(cls.logit, test, "submission.logit.csv")
```

```{r}
res.mlp <- predsave(cls.mlp, test, "submission.mlp.csv")
```